name: habibi_kitchen
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  awesome_bottom_bar: ^1.2.3
  cloud_firestore: ^4.8.3
  device_preview: ^1.1.0
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.6.2
  google_sign_in: ^6.1.4
  order_tracker: ^0.0.2
  provider: ^6.0.5
  url_launcher: ^6.1.11
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
